### ISSUE TITLE
Hi, I have some problem about SRA-uploaded fastq file.

### ISSUE THREAD

**Issue by dmsalsgh97** [MingyuYang-Yale/DBiT-seq#2]
Hi, I'm trying to understand the library structure of DBiT-seq.
I downloaded the 0725e10cL sample(SRA Acession: SRR10182230) from the GEO(GSM4096262).

In the SRR10182230_1.fastq, Read1 only has 26base length sequences like below.
![image](https://user-images.githubusercontent.com/42495757/103751223-4c6e5300-504b-11eb-9a88-4149938101bc.png)
In my think, it is a fully re-formatted structure containing Barcode B(8bp) - Barcode A(8bp) - UMI(10bp)

Then, What is Read2? In the SRR10182230_2.fastq, I couldn't find what the Read2 it is.
![image](https://user-images.githubusercontent.com/42495757/103751837-3d3bd500-504c-11eb-88cd-1bd77d84b11d.png)

Below is my understandings of DBiT-seq library structure and the seqeucing...
![image](https://user-images.githubusercontent.com/42495757/103755359-0b793d00-5051-11eb-9a76-080a6b6fe783.png)
Is it right? If it is right, Read2 in the SRR10182230_2.fastq should contain the cDNA of captured mRNA.

Thanks for sharing your effort!

**Comment by MingyuYang-Yale** [comment]
Yes, you are totally right. Read2 contains the cDNA of captured mRNA.

Best,
Mingyu

=============================
Mingyu Yang, Ph.D.
Postdoctoral Associate in Fan lab
Department of Biomedical Engineering
Yale University
55 Prospect St. MEC 103B
New Haven, CT, 06511

T: +1(203) 361-8885
E: mingyu.yang@yale.edu
=============================

**Comment by dmsalsgh97** [comment]
Thanks. 
your comment was really helpful!
